delete Notas
delete ActaDocumentos
delete ActaEstudios
delete ActaProfesionales
delete Actas

delete EstudioCentros
delete EstudioMonodrogas
delete EstudioParticipantes
delete EstudioPatrocinadores
delete EstudioTiposDocumento

delete DocumentoVersionComentarios
delete DocumentoVersionEstados
delete DocumentoVersionParticipantes
delete DocumentoVersionRecordatorios
delete NotaDocumentos
delete DocumentoVersiones
delete RecordatorioDocumentos
delete Documentos

delete Recordatorios

delete Estudios
