//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace pome.SysGEIC.Web {
    
    
    public partial class BandejaRecordatorios {
        
        /// <summary>
        /// RecordatorioControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::pome.SysGEIC.Web.Controles.RecordatorioControl RecordatorioControl1;
        
        /// <summary>
        /// PlantillaSeleccionControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::pome.SysGEIC.Web.Controles.PlantillaSeleccionControl PlantillaSeleccionControl1;
    }
}
